/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import controller.ModelTable;
import java.io.File;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import logica.Model;

/**
 *
 * @author Esteban
 */
public class View extends javax.swing.JFrame implements Observer{
    
    ModelTable model;
    Controller controller;

    public ModelTable getModel() {
        return model;
    }

    public Controller getController() {
        return controller;
    }

    public void setModelTable(ModelTable model) {
        this.model = model;
        model.addOserver(this);
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void limpiar() {
        this.jtfExpresion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        expresions = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jlinfo1 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jlinfo2 = new javax.swing.JLabel();
        jtfExpresion = new javax.swing.JTextField();
        btnAnd = new javax.swing.JButton();
        btnOr = new javax.swing.JButton();
        btnImplica = new javax.swing.JButton();
        btlDoble = new javax.swing.JButton();
        btnNegar = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        expresions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        expresions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expresionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(expresions);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jlinfo1.setText("Dar click sobre la expresion para verificarla");

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jlinfo2.setText("Añadir nueva expresión");

        btnAnd.setText("˄");
        btnAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndActionPerformed(evt);
            }
        });

        btnOr.setText("˅");
        btnOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrActionPerformed(evt);
            }
        });

        btnImplica.setText("→");
        btnImplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImplicaActionPerformed(evt);
            }
        });

        btlDoble.setText("↔ ");
        btlDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlDobleActionPerformed(evt);
            }
        });

        btnNegar.setText("⌐");
        btnNegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegarActionPerformed(evt);
            }
        });

        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlinfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCargar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jlinfo2)
                        .addGap(28, 28, 28)
                        .addComponent(jtfExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnAnd)
                        .addGap(18, 18, 18)
                        .addComponent(btnOr)
                        .addGap(18, 18, 18)
                        .addComponent(btnImplica)
                        .addGap(18, 18, 18)
                        .addComponent(btlDoble)
                        .addGap(18, 18, 18)
                        .addComponent(btnNegar)
                        .addGap(35, 35, 35)
                        .addComponent(btnClear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCargar)
                        .addComponent(btnGuardar))
                    .addComponent(jlinfo1))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlinfo2)
                    .addComponent(jtfExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnd)
                    .addComponent(btnOr)
                    .addComponent(btnImplica)
                    .addComponent(btlDoble)
                    .addComponent(btnNegar)
                    .addComponent(btnClear))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        JFileChooser open = new JFileChooser();
        open.showOpenDialog(this);
        String patch = "";
        if (open.getSelectedFile().getAbsolutePath() != null) {
            patch = open.getSelectedFile().getAbsolutePath();
        }
        if (!patch.isEmpty()) {
            controller.cargarDatos(patch);
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void expresionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expresionsMouseClicked
        if (evt.getClickCount() == 2) {
            controller.row(this.expresions.getSelectedRow());
            project1.Project1.SECUNDARY_CONTROLLER.secundaryView();
            this.setVisible(false);
        }
    }//GEN-LAST:event_expresionsMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        JFileChooser save = new JFileChooser();
        File file = null;
        if (save.showDialog(this, "Guardar") == JFileChooser.APPROVE_OPTION) {
            file = save.getSelectedFile();
            controller.guardarArchivo(file);
            if (!file.getName().endsWith("txt")) {
                Object[] mensaje = {"Error de archivo"};
                JOptionPane.showMessageDialog(View.this, mensaje, "Error", JOptionPane.OK_OPTION);
            }
            
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndActionPerformed
        this.jtfExpresion.setText(this.jtfExpresion.getText() + "˄");
    }//GEN-LAST:event_btnAndActionPerformed

    private void btnOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrActionPerformed
        this.jtfExpresion.setText(this.jtfExpresion.getText() + "˅");
    }//GEN-LAST:event_btnOrActionPerformed

    private void btnImplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImplicaActionPerformed
        this.jtfExpresion.setText(this.jtfExpresion.getText() + "→");
    }//GEN-LAST:event_btnImplicaActionPerformed

    private void btlDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlDobleActionPerformed
        this.jtfExpresion.setText(this.jtfExpresion.getText() + "↔");
    }//GEN-LAST:event_btlDobleActionPerformed

    private void btnNegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegarActionPerformed
        this.jtfExpresion.setText(this.jtfExpresion.getText() + "⌐");
    }//GEN-LAST:event_btnNegarActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        limpiar();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlDoble;
    private javax.swing.JButton btnAnd;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImplica;
    private javax.swing.JButton btnNegar;
    private javax.swing.JButton btnOr;
    private javax.swing.JTable expresions;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlinfo1;
    private javax.swing.JLabel jlinfo2;
    private javax.swing.JTextField jtfExpresion;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        this.expresions.setModel(model.getTableExpresion());
    }
}
